### ISSUE TITLE
test.yml using wrong ref

### ISSUE THREAD

**Issue by bj00rn** [thomasnordquist/MQTT-Explorer#806]
I believe the current test.yml workflow is using the wrong ref to test PRs. The commit actually being tested in the workflow is `base branch` ref since the GITHUB_REF for `pull_request_target` `PR base branch`.

The correct syntax is as follows, to check out PR head sha.

```
 - uses: actions/checkout@v3
     with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Rerun on comment
```
